"""Canonical values used by administrator reward workflows."""

VIEW_ROLES = {"admin", "finance_admin", "super_admin"}
ADJUSTMENT_ROLES = VIEW_ROLES
REVERSAL_ROLES = {"finance_admin", "super_admin"}
DIRECTIONS = {"CREDIT", "DEBIT"}

ADMIN_ADJUSTMENT_SOURCE_DIRECTIONS = {
    "ADMIN_REWARD": "CREDIT",
    "ADMIN_REVOCATION": "DEBIT",
}
ADMIN_ADJUSTMENT_SOURCES = set(ADMIN_ADJUSTMENT_SOURCE_DIRECTIONS)

REWARD_SOURCES = {
    "ADMIN_REWARD",
    "ADMIN_REVOCATION",
    "ADMIN_ADJUSTMENT_REVERSAL",
    "SOCIAL_POST_REWARD",
    "POST_REACTION_REWARD",
    "POST_REACTION_REVERSAL",
    "POST_DELETE_REVERSAL",
    "AD_IMPRESSION_REWARD",
    "AD_CLICK_REWARD",
    "ECOMMERCE_ORDER_REWARD",
    "JOB_APPLICATION_REWARD",
    "CONNECTION_REWARD",
    "SKILL_ENDORSEMENT_REWARD",
    "CME_EVENT_REGISTRATION",
    "CANDIDATE_PROFILE_REWARD",
    "ORDER_CANCEL_COIN_REFUND",
    "ORDER_CANCEL_REWARD_REVERSAL",
}
