import { useEffect, useState } from "react";
import type { SignedInAccount } from "../../lib/auth/accountTypes";
import { MemberPostHistory } from "./components/MemberPostHistory";
import { MemberProfileHeader } from "./components/MemberProfileHeader";
import { ProfessionalDetails } from "./components/ProfessionalDetails";
import { loadMemberExperiences, loadMemberSkills, loadSignedInMemberPosts, loadSignedInMemberProfile } from "./api/requests";
import type { MemberPost, ProfessionalExperience, SkillEndorsement } from "./types";
import "./styles.css";

export interface MemberProfilePageProps { signedInAccount: SignedInAccount; profileAccount?: SignedInAccount; onOpenPost?: (postId: string) => void; onOpenSettings?: () => void; }
function profileFailureMessage(error: unknown) { return error instanceof Error ? error.message : "The profile request failed."; }
export function MemberProfilePage({ signedInAccount, profileAccount, onOpenPost, onOpenSettings }: MemberProfilePageProps) { const initialAccount = profileAccount ?? signedInAccount; const isOwnProfile = initialAccount.id === signedInAccount.id; const [account, setAccount] = useState(initialAccount); const [profileError, setProfileError] = useState(""); const [posts, setPosts] = useState<MemberPost[]>([]); const [postsLoading, setPostsLoading] = useState(isOwnProfile); const [postsError, setPostsError] = useState(""); const [postReloadNumber, setPostReloadNumber] = useState(0); const [experiences, setExperiences] = useState<ProfessionalExperience[]>([]); const [skills, setSkills] = useState<SkillEndorsement[]>([]); const [professionalLoading, setProfessionalLoading] = useState(true); const [professionalError, setProfessionalError] = useState(""); const [professionalReloadNumber, setProfessionalReloadNumber] = useState(0);
  useEffect(() => { if (!isOwnProfile) { setAccount(initialAccount); setProfileError("A persisted public member-profile endpoint is not available. Showing the account identity supplied by the parent page."); return; } const controller = new AbortController(); setProfileError(""); loadSignedInMemberProfile(controller.signal).then(setAccount).catch((loadError: unknown) => { if (!controller.signal.aborted) setProfileError(profileFailureMessage(loadError)); }); return () => controller.abort(); }, [initialAccount, isOwnProfile]);
  useEffect(() => { if (!isOwnProfile) { setPosts([]); setPostsLoading(false); return; } const controller = new AbortController(); setPostsLoading(true); setPostsError(""); loadSignedInMemberPosts(controller.signal).then(setPosts).catch((loadError: unknown) => { if (!controller.signal.aborted) setPostsError(profileFailureMessage(loadError)); }).finally(() => { if (!controller.signal.aborted) setPostsLoading(false); }); return () => controller.abort(); }, [isOwnProfile, postReloadNumber]);
  useEffect(() => { const controller = new AbortController(); setProfessionalLoading(true); setProfessionalError(""); Promise.all([loadMemberExperiences(String(account.id), controller.signal), loadMemberSkills(String(account.id), controller.signal)]).then(([loadedExperiences, loadedSkills]) => { setExperiences(loadedExperiences); setSkills(loadedSkills); }).catch((loadError: unknown) => { if (!controller.signal.aborted) setProfessionalError(profileFailureMessage(loadError)); }).finally(() => { if (!controller.signal.aborted) setProfessionalLoading(false); }); return () => controller.abort(); }, [account.id, professionalReloadNumber]);
  return <main className="member-profile-page">{profileError ? <p className="profile-state profile-warning">{profileError}</p> : null}<MemberProfileHeader account={account} postCount={posts.length} isOwnProfile={isOwnProfile} onOpenSettings={onOpenSettings} /><ProfessionalDetails account={account} experiences={experiences} skills={skills} isOwnProfile={isOwnProfile} loading={professionalLoading} error={professionalError} onExperienceAdded={() => setProfessionalReloadNumber((value) => value + 1)} /><MemberPostHistory posts={posts} loading={postsLoading} error={postsError} unavailableReason={!isOwnProfile ? "The current backend has no public post-history endpoint for another member." : undefined} onRetry={() => setPostReloadNumber((value) => value + 1)} onOpenPost={onOpenPost} /></main>;
}
