import { useEffect, useState, type FormEvent } from "react";
import { Check } from "lucide-react";
import { Checkbox } from "radix-ui";
import { Button } from "../../../components/ui/Button";
import type { SignedInAccount } from "../../../lib/auth/accountTypes";
import { loadShoppingCart, placeMarketplaceOrder } from "../api/requests";
import type { MarketplaceCheckoutResult, ShoppingCartSummary } from "../types";

export interface MarketplaceCheckoutProps { signedInAccount: SignedInAccount; onBackToCart: () => void; onOrderPlaced: (result: MarketplaceCheckoutResult) => void; onRewardBalanceChanged?: (coins: number) => void; }
function checkoutFailureMessage(error: unknown) { return error instanceof Error ? error.message : "Checkout could not be completed."; }
export function MarketplaceCheckout({ signedInAccount, onBackToCart, onOrderPlaced, onRewardBalanceChanged }: MarketplaceCheckoutProps) { const [cart, setCart] = useState<ShoppingCartSummary | null>(null); const [address, setAddress] = useState(""); const [useCoins, setUseCoins] = useState(true); const [loading, setLoading] = useState(true); const [placing, setPlacing] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<MarketplaceCheckoutResult | null>(null);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); loadShoppingCart(controller.signal).then(setCart).catch((loadError: unknown) => { if (!controller.signal.aborted) setError(checkoutFailureMessage(loadError)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, []);
  async function submitCheckout(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (!address.trim()) { setError("Enter a delivery address."); return; } setPlacing(true); try { const checkoutResult = await placeMarketplaceOrder(address, useCoins); setResult(checkoutResult); onRewardBalanceChanged?.(checkoutResult.new_hu_coins); onOrderPlaced(checkoutResult); } catch (checkoutError) { setError(checkoutFailureMessage(checkoutError)); } finally { setPlacing(false); } }
  if (loading) return <p className="marketplace-state">Loading checkout...</p>;
  if (result) return <section className="checkout-result"><p>Order record created by the backend</p><h2>Order {result.order_id}</h2><dl><div><dt>Status</dt><dd>{result.status}</dd></div><div><dt>Total</dt><dd>INR {Number(result.total_amount).toFixed(2)}</dd></div><div><dt>HU Coins spent</dt><dd>{result.coins_spent}</dd></div><div><dt>HU Coins earned</dt><dd>{result.coins_earned}</dd></div><div><dt>Amount recorded for payment gateway</dt><dd>INR {Number(result.gateway_spent).toFixed(2)}</dd></div></dl>{result.gateway_spent > 0 ? <p className="marketplace-note">The current backend records this gateway amount but does not return external payment confirmation.</p> : null}</section>;
  return <section className="marketplace-checkout"><Button className="marketplace-back" variant="ghost" size="small" onClick={onBackToCart}>Back to cart</Button><header><p>Checkout</p><h2>Delivery and reward redemption</h2><span>Ordering as {signedInAccount.name}</span></header>{error ? <p className="marketplace-state marketplace-error">{error}</p> : null}{cart && cart.items.length === 0 ? <p className="marketplace-state">The cart is empty, so checkout is unavailable.</p> : null}{cart && cart.items.length > 0 ? <form onSubmit={submitCheckout}><label><span>Delivery address</span><textarea rows={4} value={address} onChange={(event) => setAddress(event.target.value)} required /></label><div className="reward-redemption-choice"><Checkbox.Root id="use-hu-coins" checked={useCoins} onCheckedChange={(checked) => setUseCoins(checked === true)}><Checkbox.Indicator><Check aria-hidden="true" /></Checkbox.Indicator></Checkbox.Root><label htmlFor="use-hu-coins">Use HU Coins, up to the backend limit of 50 percent of the product total</label></div><div className="checkout-review"><p><span>Product total</span><strong>INR {Number(cart.total).toFixed(2)}</strong></p><p><span>Available HU Coins</span><strong>{cart.hu_coins_balance}</strong></p><p><span>Maximum redeemable</span><strong>{cart.max_coins_redeemable ?? 0} coins</strong></p></div><p className="marketplace-note">Any remaining amount is recorded by the current backend as gateway spend. This screen does not claim an external payment was processed.</p><Button type="submit" disabled={placing}>{placing ? "Creating order..." : "Create order"}</Button></form> : null}</section>;
}
