import { useEffect, useState } from "react";
import { cancelMarketplaceOrder, loadMarketplaceOrder, loadMyOrders } from "../api/requests";
import type { CancelMarketplaceOrderResult, MarketplaceOrder } from "../types";

export interface MyOrdersProps { onRewardBalanceChanged?: (coins: number) => void; }
function orderFailureMessage(error: unknown) { return error instanceof Error ? error.message : "The order request failed."; }
function orderCanBeCancelled(status: string) { return ["confirmed", "processing"].includes(status.toLowerCase()); }
export function MyOrders({ onRewardBalanceChanged }: MyOrdersProps) { const [orders, setOrders] = useState<MarketplaceOrder[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [workingOrderId, setWorkingOrderId] = useState(""); const [selectedOrder, setSelectedOrder] = useState<MarketplaceOrder | null>(null); const [cancellation, setCancellation] = useState<CancelMarketplaceOrderResult | null>(null); const [reloadNumber, setReloadNumber] = useState(0);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); loadMyOrders(controller.signal).then(setOrders).catch((loadError: unknown) => { if (!controller.signal.aborted) setError(orderFailureMessage(loadError)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [reloadNumber]);
  async function openOrder(orderId: string) { setWorkingOrderId(orderId); setError(""); try { setSelectedOrder(await loadMarketplaceOrder(orderId)); } catch (loadError) { setError(orderFailureMessage(loadError)); } finally { setWorkingOrderId(""); } }
  async function cancelOrder(orderId: string) { setWorkingOrderId(orderId); setError(""); setCancellation(null); try { const response = await cancelMarketplaceOrder(orderId); setCancellation(response); onRewardBalanceChanged?.(response.new_hu_coins); setSelectedOrder(null); setReloadNumber((value) => value + 1); } catch (cancelError) { setError(orderFailureMessage(cancelError)); } finally { setWorkingOrderId(""); } }
  return <section className="my-orders"><header><p>Orders</p><h2>Your marketplace orders</h2></header>{loading ? <p className="marketplace-state">Loading orders...</p> : null}{error ? <div className="marketplace-state marketplace-error"><p>{error}</p><button type="button" onClick={() => setReloadNumber((value) => value + 1)}>Try again</button></div> : null}{cancellation ? <p className="marketplace-confirmation">{cancellation.message}. Refunded {cancellation.refunded_coins} coins and reversed {cancellation.reversed_coins} earned coins.</p> : null}{!loading && !error && orders.length === 0 ? <p className="marketplace-state">No persisted orders were returned.</p> : null}<div className="order-list">{orders.map((order) => <article key={order.id}><div><small>{order.created_at ?? "Date not supplied"}</small><h3>Order {order.id}</h3><p>Status: <strong>{order.status}</strong></p><p>INR {Number(order.total_amount).toFixed(2)}</p></div><div><button type="button" disabled={workingOrderId === order.id} onClick={() => void openOrder(order.id)}>{workingOrderId === order.id ? "Loading..." : "View details"}</button>{orderCanBeCancelled(order.status) ? <button type="button" disabled={workingOrderId === order.id} onClick={() => void cancelOrder(order.id)}>Cancel and request refund</button> : <span>Cancellation is unavailable for this status.</span>}</div></article>)}</div>{selectedOrder ? <aside className="order-details"><button type="button" onClick={() => setSelectedOrder(null)}>Close details</button><h3>Order {selectedOrder.id}</h3><p>Status: {selectedOrder.status}</p><p>Refund status: {selectedOrder.refund_status ?? "Not supplied"}</p><p>Delivery address: {selectedOrder.shipping_address ?? "Not supplied"}</p><h4>Items</h4>{selectedOrder.items?.length ? selectedOrder.items.map((item) => <p key={item.id}>{item.name ?? item.product_id} x {item.quantity}</p>) : <p>No order items were returned.</p>}{selectedOrder.tracking_timeline?.length ? <><h4>Tracking</h4>{selectedOrder.tracking_timeline.map((step) => <p key={step.step}>{step.step}: {step.status}</p>)}</> : null}</aside> : null}</section>;
}
