import { useEffect, useState } from "react";
import { Minus, Plus } from "lucide-react";
import { Tooltip } from "radix-ui";
import { Button } from "../../../components/ui/Button";
import { loadShoppingCart, removeProductFromCart, updateCartQuantity } from "../api/requests";
import type { ShoppingCartSummary } from "../types";

export interface ShoppingCartProps { onProceedToCheckout: () => void; onContinueShopping: () => void; onCartChanged?: () => void; }
function cartFailureMessage(error: unknown) { return error instanceof Error ? error.message : "The cart request failed."; }
function QuantityButton({ label, disabled, onClick, children }: { label: string; disabled: boolean; onClick: () => void; children: React.ReactNode }) {
  return <Tooltip.Root><Tooltip.Trigger asChild><Button className="cart-quantity-button" variant="secondary" size="small" aria-label={label} disabled={disabled} onClick={onClick}>{children}</Button></Tooltip.Trigger><Tooltip.Portal><Tooltip.Content className="cart-quantity-tooltip" sideOffset={6}>{label}<Tooltip.Arrow className="cart-quantity-tooltip-arrow" /></Tooltip.Content></Tooltip.Portal></Tooltip.Root>;
}
export function ShoppingCart({ onProceedToCheckout, onContinueShopping, onCartChanged }: ShoppingCartProps) {
  const [cart, setCart] = useState<ShoppingCartSummary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [changingProductId, setChangingProductId] = useState(""); const [reloadNumber, setReloadNumber] = useState(0);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); loadShoppingCart(controller.signal).then(setCart).catch((loadError: unknown) => { if (!controller.signal.aborted) setError(cartFailureMessage(loadError)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [reloadNumber]);
  async function changeQuantity(productId: string, quantity: number) { setChangingProductId(productId); setError(""); try { await updateCartQuantity(productId, quantity); setReloadNumber((value) => value + 1); onCartChanged?.(); } catch (changeError) { setError(cartFailureMessage(changeError)); } finally { setChangingProductId(""); } }
  async function removeItem(productId: string) { setChangingProductId(productId); setError(""); try { await removeProductFromCart(productId); setReloadNumber((value) => value + 1); onCartChanged?.(); } catch (removeError) { setError(cartFailureMessage(removeError)); } finally { setChangingProductId(""); } }
  return <Tooltip.Provider delayDuration={300}><section className="shopping-cart"><header><div><p>Cart</p><h2>Your selected products</h2></div><Button variant="secondary" size="small" onClick={onContinueShopping}>Continue shopping</Button></header>{loading ? <p className="marketplace-state">Loading cart...</p> : null}{error ? <div className="marketplace-state marketplace-error"><p>{error}</p><Button size="small" onClick={() => setReloadNumber((value) => value + 1)}>Try again</Button></div> : null}{!loading && cart && cart.items.length === 0 ? <p className="marketplace-state">Your cart is empty.</p> : null}{cart && cart.items.length > 0 ? <><div className="cart-items">{cart.items.map((item) => <article key={item.id}><div>{item.image_url ? <img src={item.image_url} alt="" /> : <span>No image</span>}</div><section><h3>{item.name}</h3><p>INR {Number(item.price).toFixed(2)} each</p><div className="cart-quantity"><QuantityButton label={`Decrease ${item.name} quantity`} disabled={changingProductId === item.product_id || item.quantity <= 1} onClick={() => void changeQuantity(item.product_id, item.quantity - 1)}><Minus aria-hidden="true" /></QuantityButton><strong aria-label={`${item.quantity} items`}>{item.quantity}</strong><QuantityButton label={`Increase ${item.name} quantity`} disabled={changingProductId === item.product_id || (typeof item.stock === "number" && item.quantity >= item.stock)} onClick={() => void changeQuantity(item.product_id, item.quantity + 1)}><Plus aria-hidden="true" /></QuantityButton></div><Button className="cart-remove" variant="ghost" size="small" disabled={changingProductId === item.product_id} onClick={() => void removeItem(item.product_id)}>Remove</Button></section><strong>INR {(Number(item.price) * item.quantity).toFixed(2)}</strong></article>)}</div><aside className="cart-summary"><p><span>Product total</span><strong>INR {Number(cart.total).toFixed(2)}</strong></p><p><span>HU Coins balance</span><strong>{cart.hu_coins_balance}</strong></p><p><span>Maximum redeemable</span><strong>{cart.max_coins_redeemable ?? 0} coins</strong></p><Button onClick={onProceedToCheckout}>Proceed to checkout</Button></aside></> : null}</section></Tooltip.Provider>;
}
