import { useEffect, useState } from "react";
import { loadShoppingCart, removeProductFromCart, updateCartQuantity } from "../api/requests";
import type { ShoppingCartSummary } from "../types";

export interface ShoppingCartProps { onProceedToCheckout: () => void; onContinueShopping: () => void; onCartChanged?: () => void; }
function cartFailureMessage(error: unknown) { return error instanceof Error ? error.message : "The cart request failed."; }
export function ShoppingCart({ onProceedToCheckout, onContinueShopping, onCartChanged }: ShoppingCartProps) {
  const [cart, setCart] = useState<ShoppingCartSummary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [changingProductId, setChangingProductId] = useState(""); const [reloadNumber, setReloadNumber] = useState(0);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); loadShoppingCart(controller.signal).then(setCart).catch((loadError: unknown) => { if (!controller.signal.aborted) setError(cartFailureMessage(loadError)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [reloadNumber]);
  async function changeQuantity(productId: string, quantity: number) { setChangingProductId(productId); setError(""); try { await updateCartQuantity(productId, quantity); setReloadNumber((value) => value + 1); onCartChanged?.(); } catch (changeError) { setError(cartFailureMessage(changeError)); } finally { setChangingProductId(""); } }
  async function removeItem(productId: string) { setChangingProductId(productId); setError(""); try { await removeProductFromCart(productId); setReloadNumber((value) => value + 1); onCartChanged?.(); } catch (removeError) { setError(cartFailureMessage(removeError)); } finally { setChangingProductId(""); } }
  return <section className="shopping-cart"><header><div><p>Cart</p><h2>Your selected products</h2></div><button type="button" onClick={onContinueShopping}>Continue shopping</button></header>{loading ? <p className="marketplace-state">Loading cart...</p> : null}{error ? <div className="marketplace-state marketplace-error"><p>{error}</p><button type="button" onClick={() => setReloadNumber((value) => value + 1)}>Try again</button></div> : null}{!loading && cart && cart.items.length === 0 ? <p className="marketplace-state">Your cart is empty.</p> : null}{cart && cart.items.length > 0 ? <><div className="cart-items">{cart.items.map((item) => <article key={item.id}><div>{item.image_url ? <img src={item.image_url} alt="" /> : <span>No image</span>}</div><section><h3>{item.name}</h3><p>INR {Number(item.price).toFixed(2)} each</p><div className="cart-quantity"><button type="button" disabled={changingProductId === item.product_id || item.quantity <= 1} onClick={() => void changeQuantity(item.product_id, item.quantity - 1)}>Decrease</button><strong>{item.quantity}</strong><button type="button" disabled={changingProductId === item.product_id || (typeof item.stock === "number" && item.quantity >= item.stock)} onClick={() => void changeQuantity(item.product_id, item.quantity + 1)}>Increase</button></div><button className="cart-remove" type="button" disabled={changingProductId === item.product_id} onClick={() => void removeItem(item.product_id)}>Remove</button></section><strong>INR {(Number(item.price) * item.quantity).toFixed(2)}</strong></article>)}</div><aside className="cart-summary"><p><span>Product total</span><strong>INR {Number(cart.total).toFixed(2)}</strong></p><p><span>HU Coins balance</span><strong>{cart.hu_coins_balance}</strong></p><p><span>Maximum redeemable</span><strong>{cart.max_coins_redeemable ?? 0} coins</strong></p><button type="button" onClick={onProceedToCheckout}>Proceed to checkout</button></aside></> : null}</section>;
}
