export const DOCTOR_SPECIALTY_SUGGESTIONS = [
  "General Medicine",
  "Cardiology",
  "Dermatology",
  "Pediatrics",
  "Orthopedics",
  "Gynecology",
  "Neurology",
  "Psychiatry",
  "Dentistry",
  "Physiotherapy",
  "Psychology",
  "Nutrition",
  "Other",
] as const;
