import { useState, type FormEvent } from "react";
import { Collapsible } from "radix-ui";
import { Button } from "../../../components/ui/Button";
import type { SignedInAccount } from "../../../lib/auth/accountTypes";
import { addProfessionalExperience } from "../api/requests";
import type { ProfessionalExperience, SkillEndorsement } from "../types";

export interface ProfessionalDetailsProps { account: SignedInAccount; experiences: ProfessionalExperience[]; skills: SkillEndorsement[]; isOwnProfile: boolean; loading: boolean; error: string; onExperienceAdded: () => void; }
function experienceFailureMessage(error: unknown) { return error instanceof Error ? error.message : "The experience could not be saved."; }
export function ProfessionalDetails({ account, experiences, skills, isOwnProfile, loading, error, onExperienceAdded }: ProfessionalDetailsProps) { const [showForm, setShowForm] = useState(false); const [title, setTitle] = useState(""); const [company, setCompany] = useState(""); const [location, setLocation] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState(""); const [serverMessage, setServerMessage] = useState(""); const profile = account.profile ?? {}; const verificationStatus = typeof profile.verification_status === "string" ? profile.verification_status : "Not verified";
  async function submitExperience(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaveError(""); setServerMessage(""); if (!title.trim() || !company.trim()) { setSaveError("Job title and company are required."); return; } setSaving(true); try { const response = await addProfessionalExperience({ title, company, location, startDate, endDate, description }); setServerMessage(response.message); setShowForm(false); setTitle(""); setCompany(""); setLocation(""); setStartDate(""); setEndDate(""); setDescription(""); onExperienceAdded(); } catch (submitError) { setSaveError(experienceFailureMessage(submitError)); } finally { setSaving(false); } }
  return <Collapsible.Root asChild open={showForm} onOpenChange={setShowForm}><section className="professional-details"><header><div><p>Professional details</p><h2>Experience and skills</h2></div>{isOwnProfile ? <Collapsible.Trigger asChild><Button size="small" variant="secondary">{showForm ? "Close form" : "Add experience"}</Button></Collapsible.Trigger> : null}</header><dl className="profile-facts"><div><dt>Account type</dt><dd>{account.user_type}</dd></div><div><dt>Specialty</dt><dd>{profile.specialty ?? "Not supplied"}</dd></div><div><dt>Organization</dt><dd>{profile.hospital ?? profile.company_name ?? profile.store_name ?? "Not supplied"}</dd></div><div><dt>Verification</dt><dd>{account.is_verified ? "Verified" : verificationStatus}</dd></div></dl>{serverMessage ? <p className="profile-confirmation">{serverMessage}</p> : null}<Collapsible.Content asChild><form className="experience-form" onSubmit={submitExperience}><label><span>Job title</span><input value={title} onChange={(event) => setTitle(event.target.value)} required /></label><label><span>Company</span><input value={company} onChange={(event) => setCompany(event.target.value)} required /></label><label><span>Location</span><input value={location} onChange={(event) => setLocation(event.target.value)} /></label><div><label><span>Start date</span><input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label><span>End date</span><input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label></div><label><span>Description</span><textarea rows={4} value={description} onChange={(event) => setDescription(event.target.value)} /></label>{saveError ? <p className="profile-error">{saveError}</p> : null}<Button type="submit" disabled={saving}>{saving ? "Saving..." : "Save experience"}</Button></form></Collapsible.Content>{loading ? <p className="profile-state">Loading professional records...</p> : null}{error ? <p className="profile-state profile-error">{error}</p> : null}{!loading && !error ? <><div className="experience-list"><h3>Experience</h3>{experiences.length ? experiences.map((experience) => <article key={experience.id}><strong>{experience.title}</strong><span>{experience.company}{experience.location ? `, ${experience.location}` : ""}</span><small>{experience.start_date || "Start date not supplied"} to {experience.end_date || "Present"}</small>{experience.description ? <p>{experience.description}</p> : null}</article>) : <p>No persisted experience records were returned.</p>}</div><div className="member-skills"><h3>Skills</h3>{skills.length ? skills.map((skill) => <span key={skill.skill_name}>{skill.skill_name} ({skill.endorsement_count})</span>) : <p>No persisted skill endorsements were returned.</p>}</div></> : null}</section></Collapsible.Root>;
}
